# Generated by Django 5.1.4 on 2025-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_reportimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
