# Generated by Django 5.1.4 on 2025-12-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reportcomment_user_alter_reportlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('energy', 'Energetyka'), ('water', 'Woda / kanalizacja'), ('road', 'Infrastruktura drogowa'), ('other', 'Inne')], max_length=50, null=True),
        ),
    ]
